version: '3.8'

services:
  pump-bot-server:
    build: .
    container_name: proptrex-pump-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    # Eger bot_config.json'un kalici olmasini istiyorsaniz asagidaki satiri acin
    volumes:
      - ./bot_config.json:/app/bot_config.json
